config/routes.rb
Rails.application.routes.draw do
  resources :student_paths
  devise_for :students
  root to: "quizzes#index"
  
  resources :question_options
  resources :questions
  resources :quizzes
  resources :paths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/path.rb
class Path < ApplicationRecord
    has_many :questions
    has_many :student_paths
    has_many :students, through: :student_paths
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  before_action :set_path, only: [:show, :edit, :update, :destroy]

  # GET /paths
  # GET /paths.json
  def index
    @paths = Path.all
  end

  # GET /paths/1
  # GET /paths/1.json
  def show
  end

  # GET /paths/new
  def new
    @path = Path.new
  end

  # GET /paths/1/edit
  def edit
  end

  # POST /paths
  # POST /paths.json
  def create
    @path = Path.new(path_params)

    respond_to do |format|
      if @path.save
        format.html { redirect_to @path, notice: 'Path was successfully created.' }
        format.json { render :show, status: :created, location: @path }
      else
        format.html { render :new }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paths/1
  # PATCH/PUT /paths/1.json
  def update
    respond_to do |format|
      if @path.update(path_params)
        format.html { redirect_to @path, notice: 'Path was successfully updated.' }
        format.json { render :show, status: :ok, location: @path }
      else
        format.html { render :edit }
        format.json { render json: @path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paths/1
  # DELETE /paths/1.json
  def destroy
    @path.destroy
    respond_to do |format|
      format.html { redirect_to paths_url, notice: 'Path was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_path
      @path = Path.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def path_params
      params.require(:path).permit(:title)
    end
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/views/paths/_form.html.erb
<%= form_with(model: path, local: true) do |form| %>
  <% if path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(path.errors.count, "error") %> prohibited this path from being saved:</h2>

      <ul>
      <% path.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paths/edit.html.erb
<h1>Editing Path</h1>

<%= render 'form', path: @path %>

<%= link_to 'Show', @path %> |
<%= link_to 'Back', paths_path %>

app/views/paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paths</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paths.each do |path| %>
      <tr>
        <td><%= path.title %></td>
        <td><%= link_to 'Show', path %></td>
        <td><%= link_to 'Edit', edit_path_path(path) %></td>
        <td><%= link_to 'Destroy', path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Path', new_path_path %>

app/views/paths/new.html.erb
<h1>New Path</h1>

<%= render 'form', path: @path %>

<%= link_to 'Back', paths_path %>

app/views/paths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @path.title %>
</p>

<%= link_to 'Edit', edit_path_path(@path) %> |
<%= link_to 'Back', paths_path %>