config/routes.rb
Rails.application.routes.draw do
  resources :student_paths
  devise_for :students
  root to: "quizzes#index"
  
  resources :question_options
  resources :questions
  resources :quizzes
  resources :paths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question
end

app/controllers/question_options_controller.rb
class QuestionOptionsController < ApplicationController
  before_action :set_question_option, only: [:show, :edit, :update, :destroy]

  # GET /question_options
  # GET /question_options.json
  def index
    @question_options = QuestionOption.all
  end

  # GET /question_options/1
  # GET /question_options/1.json
  def show
  end

  # GET /question_options/new
  def new
    @question_option = QuestionOption.new
  end

  # GET /question_options/1/edit
  def edit
  end

  # POST /question_options
  # POST /question_options.json
  def create
    @question_option = QuestionOption.new(question_option_params)

    respond_to do |format|
      if @question_option.save
        format.html { redirect_to @question_option, notice: 'Question option was successfully created.' }
        format.json { render :show, status: :created, location: @question_option }
      else
        format.html { render :new }
        format.json { render json: @question_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_options/1
  # PATCH/PUT /question_options/1.json
  def update
    respond_to do |format|
      if @question_option.update(question_option_params)
        format.html { redirect_to @question_option, notice: 'Question option was successfully updated.' }
        format.json { render :show, status: :ok, location: @question_option }
      else
        format.html { render :edit }
        format.json { render json: @question_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_options/1
  # DELETE /question_options/1.json
  def destroy
    @question_option.destroy
    respond_to do |format|
      format.html { redirect_to question_options_url, notice: 'Question option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_option
      @question_option = QuestionOption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_option_params
      params.require(:question_option).permit(:option_description, :correct, :question_id)
    end
end

app/helpers/question_options_helper.rb
module QuestionOptionsHelper
end

app/views/question_options/_form.html.erb
<%= form_with(model: question_option, local: true) do |form| %>
  <% if question_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_option.errors.count, "error") %> prohibited this question_option from being saved:</h2>

      <ul>
      <% question_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :question_id %>
    <%= collection_select(:question_option, :question_id, Question.all, :id, :question_description, {}, {:class =>'form-control'} )%>
  </div>


  <div class="field">
    <%= form.label :option_description %>
    <%= form.text_field :option_description %>
  </div>

  <div class="field">
    <%= form.label :correct %>
    <%= form.check_box :correct %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/question_options/edit.html.erb
<h1>Editing Question Option</h1>

<%= render 'form', question_option: @question_option %>

<%= link_to 'Show', @question_option %> |
<%= link_to 'Back', question_options_path %>

app/views/question_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question Options</h1>

<table>
  <thead>
    <tr>
      <th>Question</th> 
      <th>Option description</th>
      <th>Correct</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_options.each do |question_option| %>
      <tr>
        <td><%= question_option.question.question_description %></td>
        <td><%= question_option.option_description %></td>
        <td><%= question_option.correct %></td>
        <td><%= link_to 'Show', question_option %></td>
        <td><%= link_to 'Edit', edit_question_option_path(question_option) %></td>
        <td><%= link_to 'Destroy', question_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question Option', new_question_option_path %>

app/views/question_options/new.html.erb
<h1>New Question Option</h1>

<%= render 'form', question_option: @question_option %>

<%= link_to 'Back', question_options_path %>

app/views/question_options/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Question:</strong>
  <%= @question_option.question.question_description %>
</p>

<p>
  <strong>Option description:</strong>
  <%= @question_option.option_description %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @question_option.correct %>
</p>


<%= link_to 'Edit', edit_question_option_path(@question_option) %> |
<%= link_to 'Back', question_options_path %>