config/routes.rb
Rails.application.routes.draw do
  resources :student_paths
  devise_for :students
  root to: "quizzes#index"
  
  resources :question_options
  resources :questions
  resources :quizzes
  resources :paths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student_path.rb
class StudentPath < ApplicationRecord
  belongs_to :student
  belongs_to :path
end

app/controllers/student_paths_controller.rb
class StudentPathsController < ApplicationController
  before_action :set_student_path, only: [:show, :edit, :update, :destroy]

  # GET /student_paths
  # GET /student_paths.json
  def index
    @student_paths = StudentPath.all
  end

  # GET /student_paths/1
  # GET /student_paths/1.json
  def show
  end

  # GET /student_paths/new
  def new
    @student_path = StudentPath.new
  end

  # GET /student_paths/1/edit
  def edit
  end

  # POST /student_paths
  # POST /student_paths.json
  def create
    @student_path = StudentPath.new(student_path_params)

    respond_to do |format|
      if @student_path.save
        format.html { redirect_to @student_path, notice: 'Student path was successfully created.' }
        format.json { render :show, status: :created, location: @student_path }
      else
        format.html { render :new }
        format.json { render json: @student_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_paths/1
  # PATCH/PUT /student_paths/1.json
  def update
    respond_to do |format|
      if @student_path.update(student_path_params)
        format.html { redirect_to @student_path, notice: 'Student path was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_path }
      else
        format.html { render :edit }
        format.json { render json: @student_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_paths/1
  # DELETE /student_paths/1.json
  def destroy
    @student_path.destroy
    respond_to do |format|
      format.html { redirect_to student_paths_url, notice: 'Student path was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_path
      @student_path = StudentPath.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_path_params
      params.require(:student_path).permit(:student_id, :path_id)
    end
end

app/helpers/student_paths_helper.rb
module StudentPathsHelper
end

app/views/student_paths/_form.html.erb
<%= form_with(model: student_path, local: true) do |form| %>
  <% if student_path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_path.errors.count, "error") %> prohibited this student_path from being saved:</h2>

      <ul>
      <% student_path.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= collection_select(:student_path, :student_id, Student.all, :id, :email, {}, {:class =>'form-control'} )%>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= collection_select(:student_path, :path_id, Path.all, :id, :title, {}, {:class =>'form-control'} )%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/student_paths/edit.html.erb
<h1>Editing Student Path</h1>

<%= render 'form', student_path: @student_path %>

<%= link_to 'Show', @student_path %> |
<%= link_to 'Back', student_paths_path %>

app/views/student_paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Student Paths</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Path</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_paths.each do |student_path| %>
      <tr>
        <td><%= student_path.student.email %></td>
        <td><%= student_path.path.title %></td>
        <td><%= student_path.created_at %></td>
        <td><%= link_to 'Show', student_path %></td>
        <td><%= link_to 'Edit', edit_student_path_path(student_path) %></td>
        <td><%= link_to 'Destroy', student_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student Path', new_student_path_path %>

app/views/student_paths/new.html.erb
<h1>New Student Path</h1>

<%= render 'form', student_path: @student_path %>

<%= link_to 'Back', student_paths_path %>

app/views/student_paths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @student_path.student.email %>
</p>

<p>
  <strong>Path:</strong>
  <%= @student_path.path.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @student_path.created_at %>
</p>

<%= link_to 'Edit', edit_student_path_path(@student_path) %> |
<%= link_to 'Back', student_paths_path %>